import time 
print ("l")
print ("o")
print ("a")
print ("d")
print ("i")
print ("n")
print ("g")
print ("welcome to dragon kill game")
print ("if you die please press enter")
name = input('What is your name?\n')
print ('Hi, %s.' % name)
print ("choose your character")
print ("your character is now ugly blob fish")
print("spawning in world")
variable=input("left or right?")
if variable==("left"):
    print("you encounter a dragon")
    print("you die")
    exit()
else:
    print ("you start to walk right")

print("you encounter a female blacksmith")
variable=input("do you buy a sword or walk away")
if variable==("walk away"):
    print("a dragon appears")
    print("it breathes fire which kills you")
    print("you respawn with a sword")

else:
    print("you buy a sword")
variable=input("do you test sword and kill female or marry her")
if variable==("marry her"):
    print("you marry her and have children")
    print("a dragon appears and kills you")
    exit()
else:
    print("you kill female and level up 1 level")
    print("you are now level 2 well done")
print("a dragon appears")
print("do you try to fight dragon")
variable=input("yes? no?")
if variable ==("no"):
    print("you run away crying because you a baby")
    print("the dragon then reappears and kills you")
    exit()
else:
    print("you hit the dragon with your sword is does 1 damage")
    print("the dragon only has 999999999999999999999999999999999 more health")
print("the dragon hits you and deals 9999999999999999999999999999999999999999999999999 health")
print("you die")
print("you spawn in HELL")
print("you spawn on a rock surrounded by lava and other things")
variable=input("do you stand still or parkour")
if variable==("parkour"):
    print("you try to parkour")
    print("you fall in the lava on the first jump")
    print("you brutally burn to death in the lava")
    exit()
else:
    print("you stand still and scout the area")
print("you see a ladder and decide to climb it")
print("you see a dragon flying at you")
variable=input("do you duck or jump to the side")
if variable==("duck"):
    print("you duck down")
    print("the dragon's claws extend")
    print("they hit you")
    print("you get thrown off the platform")
    print("you fall down")
    print("you hit the platform below")
    print("half of your body is now crushed")
    print("you slowly bleed out")
    print("you die")
    exit()
else:
    print("you jump to the side")
    print("the dragon misses you")
    print("the dragon flys into a wall")
    print("it dies")
print("you get up and walk across the platform")
print("you realise the platform is crumbling")
print("you start to run")
print("you make it to a black platform thats moves to another platform")
print("you go onto the platform and watch the moving platform move back")
print("the moving platform then blows up")
print("you then see a statue")
print("you pick it up")
print("you transform into a dragon")
print("a bigger dragon flys over")
print("the bigger dragon high fives you")
print("the bigger dragon then rips off your wings")
print("you bleed to death")
print("you spawn in hell")
print("you open your eyes and your in a jail cell")
variable=input("do you try to break out or sit still")
if variable==("break out"):
    print("you throw the chair at the cell door")
    print("the cell door falls down")
    print("it make a loud noise")
    print("a dragon flys over and breathes fire")
    print("you die")
    exit()
else:
    print("you sit still in the cell")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print(".")
    print("a dragon appears in you cell")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    print("you spawn back infront of the dragon")
    print("he burns you to death using his fire breath")
    time.sleep(3)
    print("you spawn again and he bites you in half")
    print("the dragon then leaves the cell")
    print("he comes back with a gel")
    print("he puts it on your stomach and your legs grow back")
    print("he laughs at you because you have chiken legs instead of human legs")
    print("then you cry like a baby for 2 minuets")
    print("waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    print("waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    print("waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    print("waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    time.sleep(120)
    print("a dragon then appears and kills you")
    print("you DIE!!!!")
    exit()
 


 
 
 
 
    
